### ISSUE TITLE
Undocumented async device -> threadgroup copy instruction

### ISSUE THREAD

**Issue by geohot** [dougallj/applegpu#28]
In Apple's NDArrayMatrixMultiplyNNA14 kernel in MPS for matrix multiply, they use a private simdgroup API `air.simdgroup_async_copy_2d` to do an async copy from device memory to threadgroup memory, similar to `cp.async` in Nvidia PTX. This is using a currently undocumented instruction.

Relevant disassembly:
```
 228: 7e7dac098000         mov              r31, u22                        
 22e: 7e059a098010         mov              r33, u13                                                                                                                                     
 234: 7e6198098000         mov              r24, u12                                   
 23a: 2541                 <disassembly failed>                                                                                                                                          
 23c: 2d00                 <disassembly failed>                                            
 23e: 13d0                 <disassembly failed>                                                                                                                                          
 240: 0000                 <disassembly failed>                                                                                                                                          
 242: 2549                 <disassembly failed>                                                                                                                                          
 244: 4400                 <disassembly failed>                                                                                                                                          
 246: 13d0                 <disassembly failed>                                           
 248: 0000                 <disassembly failed>                                          
 24a: 520e00000000         pop_exec         r0l, 1                                        
 250: f592                 TODO.unkF59      0, 2                                       
 252: f592                 TODO.unkF59      0, 2                                        
 254: 520e00000000         pop_exec         r0l, 1                                                                                                                                       
 25a: 0e66146106001000     iadd             r25h, u10l, r19l, lsl 2                         
 262: 0e54167106001000     iadd             r21l, u11l, r19h, lsl 2                         
 26a: 6800                 threadgroup_barrier                                              
 26c: 69b5330234810010     threadgroup_load i32, xy, r45_r46, r25h, 0                       
 274: 699d2a0234810010     threadgroup_load i32, xy, r39_r40, r21l, 0                       
 27c: 69a5330234840210     threadgroup_load i32, xy, r41_r42, r25h, 128                     
 284: 69952a2234840010     threadgroup_load i32, xy, r37_r38, r21l, 2                                                                                                                    
 28c: ef454eae25a20285     simd_matrix_fmadd32 r17_r18.cache, r39_r40, r45_r46, r17_r18.cache
 294: 6f454a2e25620285     simd_matrix_fmadd32 r17_r18, r37_r38, r41_r42, r17_r18
```

Will try to add it, but if I don't get to it, I wanted to file this issue for the next person who finds the secret async.

**Comment by geohot** [comment]
I'd also be very interested in a way to use this from metal.

```
declare %struct._simdgroup_event_t* @air.simdgroup_async_copy_2d.p3i8.p1i8(i64, i64, i8 addrspace(3)* nocapture writeonly, i64, i64, <2 x i64>, i8 addrspace(1)* nocapture readonly, i64, i64, <2 x i64>, <2 x i64>, i32) local_unnamed_addr #9
```

is the signature of the LLVM intrinsic, but I don't see how it's broken out, nor do I see a way to call LLVM intrinsics. I can't find anything like `__metal_simdgroup_matrix_8x8_load` for it.

**Comment by lin72h** [comment]
THE GeoHot, wow, Thanks for hacking into AGX

**Comment by philipturner** [comment]
The SIMD-group copy API exists is part of the Metal Standard Library, headers `metal_simdgroup_async` and `metal_simdgroup_future`. The first header includes the intrinsic you're referencing.

Apple probably introduced the API with their A14 chip. That allowed them to harness the SIMD-scoped matrix multiply instructions. `NDArrayMatrixMultiplyNNA14` is specialized for the A14, which has half the FP32 compute power of M1 and A15. If you're optimizing for generic AS, beware of the difference. Another MPS kernel should be optimized for `A14X`.

**Comment by geohot** [comment]
Yea, I got it to work, but I had to install Xcode. I didn't find that API in the system Metal.

**Comment by philipturner** [comment]
I'm trying to locate the header for SIMD-group async copies, and I can't find it now (Xcode 14.3). metal_simdgroup_async and metal_simdgroup_future are absent from the Metal stdlib headers directory. @geohot are you still able to find them? If Apple removed them, I may need to create something like [opencl-metal-stdlib](https://github.com/philipturner/opencl-metal-stdlib) to re-expose the AIR symbols.

**Comment by philipturner** [comment]
If you download the Xcode 14.2 app from Apple's downloads archive, the `metal_simdgroup_async` and `metal_simdgroup_future` headers are there. You need the full 7 GB app, not just the command-line tools. Then go to:

```
/Applications/Xcode 14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/metal/macos/lib/clang/31001.667/include/metal
```
