### ISSUE TITLE
Suggestion for C architecture

### ISSUE THREAD

**Issue by DarkShadow44** [dougallj/applegpu#3]
Hello there,

since the target probably is to (eventually) make a working driver, wouldn't it make sense to use C code? Then the code could just be copied and used as part of a driver,  the tests would already cover the code.

Internally I'd use structs to keep track of the instructions, something like
```
enum instruction_type {
    INSTRUCTION_TYPE_IADD,
    INSTRUCTION_TYPE_IMUL,
    //...
};
struct instruction_data_iadd {
    int source;
    int dest;
    //...
};
struct instruction_data_imul {
    int source;
    int dest;
    //...
};
union instruction_data
{
    struct instruction_data_iadd iadd;
    struct instruction_data_imul imul;
};
struct instruction {
    enum instruction_type type;
    union instruction_data data;
};
```

I'd imagine it like the following:
- Have an assembler function to turn text-assembly into internal structs
- Have an assembler function to turn internal structs into bytecode
- Have emulator work on internal structs
- Have a disassembler function to turn bytecode into internal structs
- Have a disassembler function to turn internal structs into text-assembly

The advantage would be that we could, for example, use LLVM output to generate the internal structs which can than be turned into platform specific bytecode. Assuming that the GPU bytecode an change next generation, this would abstract that a bit. It should also be easier than generating text-assembly code and then parsing said text again in the next step.

For tests I would run the following series:
- Use bytecode with comments what the instructions do as input
- Run disassembler functions to get internal structs and then text-assembly
- Feed text-assembly into assembler functions to turn back into internal structs and then bytecode
- Compare generated bytecode to source, must be equal
- Run emulator on internal structs to get output - compare that against output from real GPU.
This should test all functions and our understanding of the bytecode, if I'm not wrong.

What would you think of that approach? And would you even be interested in turning this into C-Code? IMHO it would make sense to prepare for a driver, but I understand when you want to continue your way - it's your project after all.

**Comment by dougallj** [comment]
Thanks for writing this up! Unfortunately, and admittedly confusingly, my personal goal is to understand and generate accurate documentation for the hardware, rather than to make a driver, which is why I've made this a separate project from [AsahiLinux/gpu](https://github.com/AsahiLinux/gpu), and why this project is going to stay in Python - it's easier for me, personally, to do quick and dirty things in the ongoing effort to decide on the difference between instructions and operands.

The design you propose sounds great to me, and Chris and Alyssa are definitely interested in building a driver, and a C assembler and disassembler (although likely not emulator? and almost certainly not HTML documentation generation).

**Comment by DarkShadow44** [comment]
Thanks for the quick response!



> ! Unfortunately, and admittedly confusingly, my personal goal is to understand and generate accurate documentation for the hardware, rather than to make a driver, which is why I've made this a separate project from [AsahiLinux/gpu](https://github.com/AsahiLinux/gpu), and why this project is going to stay in Python - it's easier for me, personally, to do quick and dirty things in the ongoing effort to decide on the difference between instructions and operands.

No no, that makes perfect sense. When you're good in python (which I am not) it's very useful for rapid iterations. And having proper documentation (thanks for your efforts btw) is certainly extremely useful.

I best turn this into a separate project then, maybe later it could be useful/merged into  [AsahiLinux/gpu](https://github.com/AsahiLinux/gpu) later on.

Since I'm probably also taking part in instruction analysis, which would be the best way to contact you with new findings?
