### ISSUE TITLE
Android emulation support

### ISSUE THREAD

**Issue by narendersaini32** [dougallj/applegpu#60]
I know this is not the correct place but I will ask anyway. Recently Mumu player pro released an android emulator for apple silicon. Currently there is only two android emulator one is android studio AVD (very poor performance) and Mumu player pro (excellent performance but paid). Is there any way to run android on apple silicon like Qemu or something? please guide.

**Comment by dougallj** [comment]
If you know this is not the correct place, please don't ask. It has nothing to do with this project, so I do not know, and I cannot help you.
